#!/bin/sh
#
# NOTES
# - We use absolute paths instead of "/usr/bin/env prebackup" for security
#   reasons (think about implications of RUN_AS=root).
set -eu

: ${DESTDIR:=}
: ${PREFIX:="/usr/local"}

BIN_DIR="$PREFIX/bin"
SHARE_DIR="$PREFIX/share/prebackup"

sed_inplace() {
	if sed --version >/dev/null 2>&1; then
		sed -r -i'' "$@"  # GNU or Busybox sed
	else
		sed -E -i '' "$@"  # BSD sed
	fi
}

cd "$(dirname "$0")"

install -Dv -m 755 bin/prebackup "${DESTDIR}${BIN_DIR}"/prebackup

find lib -type f ! -name '*.sh' | while read path; do
	install -Dv -m 755 "$path" "${DESTDIR}${SHARE_DIR}"/$(basename $path)
done

install -Dv -m 644 lib/utils.sh "${DESTDIR}${SHARE_DIR}"/utils.sh

if [ "$BIN_DIR" != '/usr/local/bin' ]; then
	sed_inplace "s|#!/usr/local/bin/prebackup|#!$BIN_DIR/prebackup|" \
		"${DESTDIR}${SHARE_DIR}"/*
fi

if [ "$SHARE_DIR" != '/usr/local/share/prebackup' ]; then
	sed_inplace "s|/usr/local/share/prebackup|$SHARE_DIR|" \
		"${DESTDIR}${BIN_DIR}"/prebackup
fi
