#!/bin/sh
#
# NOTES
# - Command "perl -pi" is a replacement for "sed -i" (edit files in-place) that
# 	doesn't work the same on GNU and BSD.
# - We use absolute paths instead of "/usr/bin/env prebackup" for security
#   reasons (think about implications of RUN_AS=root).
set -eu

: ${DESTDIR:=}
: ${PREFIX:="/usr/local"}

BIN_DIR="$PREFIX/bin"
SHARE_DIR="$PREFIX/share/prebackup"

cd "$(dirname "$0")"

install -Dv -m 755 bin/prebackup "${DESTDIR}${BIN_DIR}"/prebackup

find lib -type f ! -name '*.sh' | while read path; do
	install -Dv -m 755 "$path" "${DESTDIR}${SHARE_DIR}"/$(basename $path)
done

install -Dv -m 644 lib/utils.sh "${DESTDIR}${SHARE_DIR}"/utils.sh

if [ "$BIN_DIR" != '/usr/local/bin' ]; then
	perl -pi -e "s|#!/usr/local/bin/prebackup|#!$BIN_DIR/prebackup|" \
		"${DESTDIR}${SHARE_DIR}"/*
fi

if [ "$SHARE_DIR" != '/usr/local/share/prebackup' ]; then
	perl -pi -e "s|/usr/local/share/prebackup|$SHARE_DIR|" \
		"${DESTDIR}${BIN_DIR}"/prebackup
fi
