#!/bin/sh
#
# NOTES
# - Command "perl -pi" is a replacement for "sed -i" (edit files in-place) that
# 	doesn't work the same on GNU and BSD.
# - We use absolute paths instead of "/usr/bin/env prebackup" for security
#   reasons (think about implications of RUN_AS=root).
set -e

PREFIX="${PREFIX:-/usr/local}"
BIN_DIR="${PREFIX}/bin"
SHARE_DIR="${PREFIX}/share/prebackup"

mkdir -p "$BIN_DIR"
cp -v bin/prebackup "$BIN_DIR"/

mkdir -p "$SHARE_DIR"
cp -v lib/* "$SHARE_DIR"/

if [ "$SHARE_DIR" != '/usr/local/share/prebackup' ]; then
	perl -pi -e "s|/usr/local/share/prebackup|${SHARE_DIR}/prebackup|" \
		"$BIN_DIR"/prebackup
fi

if [ "$BIN_DIR" != '/usr/local/bin' ]; then
	perl -pi -e "s|#!/usr/local/bin/prebackup|#!${BIN_DIR}/prebackup|" \
		"$SHARE_DIR"/*
fi
