= PreBackup
Jakub Jirutka <https://github.com/jirutka[@jirutka]>

TODO

== Script Format

PreBackup script is a Plain Old Shell Script (actually a Bash script to be precise) with few simple conventions (just like OpenRC runscripts, ebuilds etc.)

[source, sh]
----
#!/usr/local/bin/prebackup
# vim: set ft=sh ts=4:

setup() {
    echo 'Run before pre-backup and post-backup function.'
}

pre-backup() {
    echo 'Run before actual backup.'
}

post-backup() {
    echo 'Run after actual backup.'
}
----


== Configuration

TODO


== Predefined Variables

This section describes predefined variables available in config files and prebackup scripts.

All variables have sensible default value that may be overriden in global `prebackup.conf` or job’s `config` file.
Uppercase variables are read-only for prebackup script, but can be modified in config files (except `SCRIPT_DIR`).


NAME::
  Name of the “job”.
  Default is basename of `$SCRIPT_DIR`, i.e. name of directory where the sourced script resides.

RUN_AS::
  User to run the script.
  If you execute the script as a different user than the one specified by `$RUN_AS`, then it will switch to the specified user using `su`.
  Default is empty, i.e. do not switch user.

SYSLOG::
  Redirect stdout and stderr to syslog (yes/no)? Default is `yes`.

SYSLOG_TAG::
  Tag to mark every line sent to syslog.
  This is called a program name in syslog-ng.
  Default is `backup:$NAME`.

TARGET_DIR::
  Base path of directory where to store files to be backed up by a backup software.
  Default is `/var/tmp/backup`.

TEMP_DIR::
  Base path of directory where to store temporary files for prebackup scripts.
  Default is `/tmp/prebackup`.

VERBOSE::
  Log even debug messages (yes/no)? Default is `no`.

target_dir::
  Path of directory where to store files for a particular “job” (i.e. generated by the sourced script) to be backed up by a backup software.
  Default is `$TARGET_DIR/$NAME`.

temp_dir::
  Path of directory where to store temporary files for the sourced script.


== Predefined Functions

The following functions (defined in link:lib/utils.sh[utils.sh]) are available in prebackup scripts.

fail()::
  Log error message and exit.

  * $1: message
  * $2: exit code (default: `1`)

info()::
  Log info message.

  * $1: message

debug()::
  Log debug message if `$VERBOSE=yes`.

  * $1: message

required-var()::
  If the specified variable is empty, then log error message and exit.

  * $1: variable name


== Directory Structure

----
/
|-- etc
|   `-- bacula
|       |-- service1
|       |   |-- config
|       |   |-- post-backup ---------+
|       |   `-- pre-backup ----------+
|       `-- serviceN                 |
|       |   |-- config               |
|       |   |-- post-backup ------+  |
|       |   `-- pre-backup -------+  |
|       `-- prebackup.conf        |  |
`-- usr(/local)                   |  |
    |-- bin                       |  |
    |   `-- prebackup             |  |
    `-- share                     |  |
        `-- prebackup             |  |
            |-- btrfs-snapshot <--+  |
            |-- postgresql <---------+
            `-- ...
----

== License

This project is licensed under http://opensource.org/licenses/MIT/[MIT License].
