= PreBackup
Jakub Jirutka <https://github.com/jirutka[@jirutka]>

This project aims to provide simple conventions and support for writing {pre,post}-backup scripts with minimal boilerplate, and also provide some common scripts (e.g. for Btrfs snapshots, PostgreSQL…).

The first thing we should clarify: this project is _not_ a backup solution.
So what it actually is?
Well, many backup solutions, like http://www.bacula.org[Bacula] or just simple rsync, work only with files.
The problem is that you often can’t just copy bunch of files from a running system.
You need to dump a SQL database, create a snapshot on Btrfs/ZFS/LVM, … to prepare files that will be actually backed up.
When the backup is done, then you usually want to remove dumps, destroy snapshots etc.
Here comes on the scene PreBackup.

PreBackup is a supplement to a file-oriented backup software, its task is to prepare files to be backed up and do cleanup when it’s done.

It was originally written to be used with Bacula, but it’s totally independent from it.
The only assumption we have is that a backup software is able to execute some command before and after it do a backup.


== Installation

=== Gentoo

. Add https://github.com/cvut/gentoo-overlay[CTU’s Gentoo Overlay] to your repos.conf or Layman (read https://github.com/cvut/gentoo-overlay#usage[howto]).
. `emerge app-backup/prebackup`

=== Manually

TBD


== Script Format

PreBackup script is a Plain Old Shell Script (actually a Bash script to be precise) with few simple conventions (just like OpenRC runscripts, ebuilds etc.)

You should use https://en.wikipedia.org/wiki/Shebang_%28Unix%29[shebang] with path of the master link:bin/prebackup[prebackup] script.
Then you must define functions `pre-backup`, `post-backup` and optionally `setup`.

setup()::
  If defined, then this function is executed before each `pre-backup()` and `post-backup()`, in the same environment.
  You may use it to check if required variables are set (using `required-var()`), to define some common variables or anything else that should be run before `pre-backup()` and `post-backup()`.

pre-backup()::
  This function is executed when you run the script as a file named `pre-backup` (e.g. using symlink) or with argument `-c pre-backup`.
  As the name suggests, it should be run _before_ actual backup, e.g. to dump database, create filesystem snapshot, …

post-backup()::
  This function is executed when you run the script as a file named `post-backup` (e.g. using symlink) or with argument `-c post-backup`.
  It should be run _after_ actual backup, e.g. to clean database dumps, destroy filesystem snapshot, …

[source, sh]
.Prebackup Script Template
----
#!/usr/local/bin/prebackup
# vim: set ft=sh ts=4:

setup() {
    echo 'Run before pre-backup and post-backup function.'
}

pre-backup() {
    echo 'Run before actual backup.'
}

post-backup() {
    echo 'Run after actual backup.'
}
----


== Configuration

There are two places where you can define variables for a prebackup script:

* `/etc/bacula/prebackup.conf` – global configuration file (you can modify this path in link:bin/prebackup[]),
* `./config` – local configuration file located in the same directory as the pair of `pre-backup` and `post-backup` symlinks (or file and symlink) used to run the script for a particular job.

These files are nothing more than another shell scripts, but you _should_ define only variables here.
The files are sourced in the defined order before an actual prebackup script.
If both files exist and define the same variable, then local config overrides the global.


== Predefined Variables

This section describes predefined variables available in config files and prebackup scripts.

All variables have sensible default value that may be overriden in global `prebackup.conf` or job’s `config` file.
Uppercase variables are read-only for prebackup script, but can be modified in config files (except `SCRIPT_DIR`).


NAME::
  Name of the “job”.
  Default is basename of `$SCRIPT_DIR`, i.e. name of directory where the sourced script resides.

RUN_AS::
  User to run the script.
  If you execute the script as a different user than the one specified by `$RUN_AS`, then it will switch to the specified user using `su`.
  Default is empty, i.e. do not switch user.

SYSLOG::
  Redirect stdout and stderr to syslog (yes/no)? Default is `yes`.

SYSLOG_TAG::
  Tag to mark every line sent to syslog.
  This is called a program name in syslog-ng.
  Default is `backup:$NAME`.

TARGET_DIR::
  Base path of directory where to store files to be backed up by a backup software.
  Default is `/var/tmp/backup`.

TEMP_DIR::
  Base path of directory where to store temporary files for prebackup scripts.
  Default is `/tmp/prebackup`.

VERBOSE::
  Log even debug messages (yes/no)? Default is `no`.

target_dir::
  Path of directory where to store files for a particular “job” (i.e. generated by the sourced script) to be backed up by a backup software.
  Default is `$TARGET_DIR/$NAME`.

temp_dir::
  Path of directory where to store temporary files for the sourced script.


== Predefined Functions

The following functions (defined in link:lib/utils.sh[utils.sh]) are available in prebackup scripts.

fail()::
  Log error message and exit.

  * $1: message
  * $2: exit code (default: `1`)

info()::
  Log info message.

  * $1: message

debug()::
  Log debug message if `$VERBOSE=yes`.

  * $1: message

required-var()::
  If the specified variable is empty, then log error message and exit.

  * $1: variable name


== Recommended Directory Structure

----
/
|-- etc
|   `-- bacula
|       |-- service1
|       |   |-- config
|       |   |-- post-backup ---------+
|       |   `-- pre-backup ----------+
|       `-- serviceN                 |
|       |   |-- config               |
|       |   |-- post-backup ------+  |
|       |   `-- pre-backup -------+  |
|       `-- prebackup.conf        |  |
`-- usr(/local)                   |  |
    |-- bin                       |  |
    |   `-- prebackup             |  |
    `-- share                     |  |
        `-- prebackup             |  |
            |-- btrfs-snapshot <--+  |
            |-- postgresql <---------+
            `-- ...
----

== License

This project is licensed under http://opensource.org/licenses/MIT/[MIT License].
